### ISSUE TITLE
ImportError: cannot import name 'parse_rule'

### ISSUE THREAD

**Issue by Smassard82** [dstrigl/HtREST#165]
Hi, 

Unfortunately i have a problem running htRest: 
Errormessage :ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/home/pi/venv/htrest/lib/python3.7/site-packages/werkzeug/routing/__init__.py) (see also below)

Thank you very much for any help.

Regards

```
Start Heliotherm heat pump REST API server v0.1.11.
Namespace(baudrate=115200, bool_as_int=True, debug=False, device='/dev/ttyUSB0', host='0.0.0.0', logging_config='/home/pi/venv/htrest/lib/python3.7/site-packages/htrest/logging.conf', no_param_verification=True, port=8777, read_only=True, user='')
2022-09-12 09:46:18,378 INFO [htrest.app|create_app]: open connection to heat pump (<htheatpump.htheatpump.HtHeatpump object at 0xb64f41d0>)
2022-09-12 09:46:18,407 INFO [htrest.app|create_app]: successfully connected to heat pump #121650
2022-09-12 09:46:18,427 INFO [htrest.app|create_app]: software version = 3.0.8 (2593)
2022-09-12 09:46:18,443 INFO [htrest.app|create_app]: *** created Flask app <Flask 'htrest.app'> with config <Config {'ENV': 'production', 'DEBUG': False, 'TESTING': False, 'PROPAGATE_EXCEPTIONS': None, 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SECRET_KEY': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': None, 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': True, 'JSON_SORT_KEYS': True, 'JSONIFY_PRETTYPRINT_REGULAR': False, 'JSONIFY_MIMETYPE': 'application/json', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093, 'SWAGGER_UI_DOC_EXPANSION': 'list', 'RESTX_VALIDATE': True, 'RESTX_MASK_SWAGGER': False, 'ERROR_404_HELP': False, 'BUNDLE_ERRORS': True}>
Traceback (most recent call last):
  File "/home/pi/venv/htrest/bin/htrest", line 10, in <module>
    sys.exit(main())
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/htrest/__main__.py", line 189, in main
    args.no_param_verification,
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/htrest/app.py", line 85, in create_app
    from htrest.apiv1 import blueprint as apiv1
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/htrest/apiv1.py", line 25, in <module>
    from flask_restx import Api
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/flask_restx/__init__.py", line 5, in <module>
    from .api import Api  # noqa
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/flask_restx/api.py", line 50, in <module>
    from .swagger import Swagger
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/flask_restx/swagger.py", line 18, in <module>
    from werkzeug.routing import parse_rule
ImportError: cannot import name 'parse_rule' from 'werkzeug.routing' (/home/pi/venv/htrest/lib/python3.7/site-packages/werkzeug/routing/__init__.py)

```

**Comment by dstrigl** [comment]
Please try the following:
https://stackoverflow.com/questions/73105877/importerror-cannot-import-name-parse-rule-from-werkzeug-routing

**Comment by Smassard82** [comment]
Thank you very much.
I ll try the workaround with the older versions

But tryin to install the setup.py i get an other error:
```
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    version=get_version(),
  File "setup.py", line 24, in get_version
    return re.search(regex, read(*path)).group("version")
  File "setup.py", line 16, in read
    with open(filename, encoding="utf-8", mode="rt") as fp:
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by Smassard82** [comment]
Thank you very much. I managed to downgrad fask werkzeuge etc. no is working

**Comment by dstrigl** [comment]
This should help (run inside your venv):
````
pip3 install Werkzeug==2.1.2 --upgrade
pip3 install flask==2.1.3 --upgrade
````
