### ISSUE TITLE
No module named 'werkzeug' armbian 

### ISSUE THREAD

**Issue by reset12** [dstrigl/HtREST#344]
I tried to install HtREst on a new System with the following error:

Traceback (most recent call last):
  File "/usr/local/bin/htrest", line 33, in <module>
    sys.exit(load_entry_point('htrest==0.1.11', 'console_scripts', 'htrest')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/htrest", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/htrest-0.1.11-py3.11.egg/htrest/__main__.py", line 37, in <module>
    from .app import create_app
  File "/usr/local/lib/python3.11/dist-packages/htrest-0.1.11-py3.11.egg/htrest/app.py", line 26, in <module>
    from flask import Flask, current_app
  File "/usr/local/lib/python3.11/dist-packages/flask-3.0.3-py3.11.egg/flask/__init__.py", line 5, in <module>
    from . import json as json
  File "/usr/local/lib/python3.11/dist-packages/flask-3.0.3-py3.11.egg/flask/json/__init__.py", line 6, in <module>
    from ..globals import current_app
  File "/usr/local/lib/python3.11/dist-packages/flask-3.0.3-py3.11.egg/flask/globals.py", line 6, in <module>
    from werkzeug.local import LocalProxy
ModuleNotFoundError: No module named 'werkzeug'

Distributor ID:	Debian
Description:	Armbian 24.8.2 bookworm
Release:	12
Codename:	bookworm

Install Commands:
python3 -m venv /home/t759f/venv
/home/user/venv/bin/pip install HtREST --upgrade

How can i solve it ?
with regards
reset12

**Comment by dstrigl** [comment]
Just try the following:
```
pip3 install Werkzeug==2.1.2 --upgrade
pip3 install flask==2.1.3 --upgrade
```

**Comment by reset12** [comment]
It doesnt work.

'user@odroidxu4:~$ /home/user/venv/bin/pip3 install flask==2.1.3 --upgrade
Collecting flask==2.1.3
  Downloading Flask-2.1.3-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 1.2 MB/s eta 0:00:00
Requirement already satisfied: Werkzeug>=2.0 in ./venv/lib/python3.11/site-packages (from flask==2.1.3) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in ./venv/lib/python3.11/site-packages (from flask==2.1.3) (3.1.4)
Requirement already satisfied: itsdangerous>=2.0 in ./venv/lib/python3.11/site-packages (from flask==2.1.3) (2.2.0)
Requirement already satisfied: click>=8.0 in ./venv/lib/python3.11/site-packages (from flask==2.1.3) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from Jinja2>=3.0->flask==2.1.3) (2.1.5)
Installing collected packages: flask
  Attempting uninstall: flask
    Found existing installation: Flask 2.0.3
    Uninstalling Flask-2.0.3:
      Successfully uninstalled Flask-2.0.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
htrest 0.1.11 requires Flask==2.0.3, but you have flask 2.1.3 which is incompatible.
Successfully installed flask-2.1.3
user@odroidxu4:~$ /home/user/venv/bin/pip3 install flask==2.1.2 --upgrade
Collecting flask==2.1.2
  Downloading Flask-2.1.2-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 1.1 MB/s eta 0:00:00
Requirement already satisfied: Werkzeug>=2.0 in ./venv/lib/python3.11/site-packages (from flask==2.1.2) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in ./venv/lib/python3.11/site-packages (from flask==2.1.2) (3.1.4)
Requirement already satisfied: itsdangerous>=2.0 in ./venv/lib/python3.11/site-packages (from flask==2.1.2) (2.2.0)
Requirement already satisfied: click>=8.0 in ./venv/lib/python3.11/site-packages (from flask==2.1.2) (8.1.7)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from Jinja2>=3.0->flask==2.1.2) (2.1.5)
Installing collected packages: flask
  Attempting uninstall: flask
    Found existing installation: Flask 2.1.3
    Uninstalling Flask-2.1.3:
      Successfully uninstalled Flask-2.1.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
htrest 0.1.11 requires Flask==2.0.3, but you have flask 2.1.2 which is incompatible.
Successfully installed flask-2.1.2
user@odroidxu4:~$ htrest -d /dev/ttyUSB0 -b 19200 --host localhost --port 8777 --read-only &
[1] 2269
user@odroidxu4:~$ Traceback (most recent call last):
  File "/usr/local/bin/htrest", line 33, in <module>
    sys.exit(load_entry_point('htrest==0.1.11', 'console_scripts', 'htrest')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/htrest", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/htrest-0.1.11-py3.11.egg/htrest/__main__.py", line 37, in <module>
    from .app import create_app
  File "/usr/local/lib/python3.11/dist-packages/htrest-0.1.11-py3.11.egg/htrest/app.py", line 26, in <module>
    from flask import Flask, current_app
  File "/usr/local/lib/python3.11/dist-packages/flask-3.0.3-py3.11.egg/flask/__init__.py", line 5, in <module>
    from . import json as json
  File "/usr/local/lib/python3.11/dist-packages/flask-3.0.3-py3.11.egg/flask/json/__init__.py", line 6, in <module>
    from ..globals import current_app
  File "/usr/local/lib/python3.11/dist-packages/flask-3.0.3-py3.11.egg/flask/globals.py", line 6, in <module>
    from werkzeug.local import LocalProxy
ModuleNotFoundError: No module named 'werkzeug'
`

**Comment by dstrigl** [comment]
Can you create a fresh new venv, install HtREST and export the installed modules with pip freeze to take a look on it.

**Comment by dstrigl** [comment]
Maybe it's the problem that Flask-BasicAuth (and/or some of the other needed modules) doesn't work under Python 3.11?
I didn't test HtREST or htheatpump under Python 3.11 so far.
Can you test it with Python 3.10?

**Comment by reset12** [comment]
I got it working with Python 3.10 with the following commands :+1: 
# install with pyenv
sudo apt install libreadline-dev
sudo apt-get install libffi-dev
sudo apt-get install libssl-dev 
sudo apt install libsqlite3-dev
sudo apt install liblzma-dev
sudo apt-get install libbz2-dev
sudo apt-get install python3-tk python3-dev tk-dev
curl https://pyenv.run | bash
who | awk '{print $1}'| echo "export PATH=$PATH:/home/"$(</dev/stdin)"/.pyenv/bin/" >/tmp/rc
who | awk '{print $1}'| cat /tmp/rc >>/home/"$(</dev/stdin)"/.bashrc
#exit shell and start new to get changes
pyenv install 3.10
pyenv versions
pyenv virtualenv 3.10 htrest
pyenv local htrest
pyenv which python
who | awk '{print $1}'|echo 'eval "$(pyenv init -)"' >>/home/"$(</dev/stdin)"/.bashrc
who | awk '{print $1}'|echo 'eval "$(pyenv virtualenv-init -)"' >>/home/"$(</dev/stdin)"/.bashrc
pyenv activate htrest
wget https://github.com/dstrigl/HtREST/archive/refs/heads/master.zip
unzip master.zip
cd HtREST-*
who | awk '{print $1}'|sudo /home/"$(</dev/stdin)"/.pyenv/versions/htrest/bin/python setup.py install

Start with:
who | awk '{print $1}'|/home/"$(</dev/stdin)"/.pyenv/shims/htrest -d /dev/ttyUSB0 -b 19200 --host localhost --port 8777 --read-only &
