### ISSUE TITLE
Error starting server

### ISSUE THREAD

**Issue by Smassard82** [dstrigl/HtREST#83]
Hi,

When i try to start htrest  on my RPi 4 there seems to be an error:

`Traceback (most recent call last):
  File "/home/pi/venv/htrest/bin/htrest", line 10, in <module>
    sys.exit(main())
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/htrest/__main__.py", line 195, in main
    threaded=False,
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/werkzeug/serving.py", line 1005, in inner
    fd=fd,
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/werkzeug/serving.py", line 863, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/pi/venv/htrest/lib/python3.7/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address`

When looking into the journalctl: 
`-- Logs begin at Thu 2019-02-14 11:11:59 CET. --
Jan 24 16:47:14 1wirePI htrest[1098]:     HTTPServer.__init__(self, server_address, handler)
Jan 24 16:47:14 1wirePI htrest[1098]:   File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
Jan 24 16:47:14 1wirePI htrest[1098]:     self.server_bind()
Jan 24 16:47:14 1wirePI htrest[1098]:   File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
Jan 24 16:47:14 1wirePI htrest[1098]:     socketserver.TCPServer.server_bind(self)
Jan 24 16:47:14 1wirePI htrest[1098]:   File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
Jan 24 16:47:14 1wirePI htrest[1098]:     self.socket.bind(self.server_address)
Jan 24 16:47:14 1wirePI htrest[1098]: OSError: [Errno 99] Cannot assign requested address
Jan 24 16:47:14 1wirePI systemd[1]: htrest.service: Main process exited, code=exited, status=1/FAILURE
Jan 24 16:47:14 1wirePI systemd[1]: htrest.service: Failed with result 'exit-cod`

The connection to the heatpump seems to work but i cant acces the webUI

Unfortunatly i dont know whta to do.

Thank you very much in advance for any help.

**Comment by dstrigl** [comment]
Hi @Smassard82,

the error message indicates that the local IP address you are passing to the application is still used by another process (or you are not allowed to use this IP address/port).

What's the IP address and port number you are passing under the arguments `--host` and `--port` to the application?

`$ htrest -d /dev/ttyUSB0 -b 115200 --host 192.168.11.99 --port 8777 --read-only`

Regards,
Daniel.

**Comment by Smassard82** [comment]
Hi,

Thank you very much. You were rigth, there was an error in the network configuration!

Thank you very much for your quick reply!

Regards
